// this would normally come from a typescript file generated by ts-proto based on our proto files

export type SearchItemsRequest = {
    // range of 1-N filters we could send up, we'll just use simple search and page number as an example
    searchText: string;
    page: number;
};

export type SearchItemsResponse = {
    items: Array<Item>;
    totalResults: number;
};

export type Item = {
    name: string;
};
